type I={symbol:string;spot:number;future:number|null;vwap:number|null;chg:number;chgPct:number;atm:number;pcrOI:number;pcrCOI:number;support:number;resistance:number};
type M={symbol:string;price:number;chg:number}; type S={name:string;chg:number};
const f=(n:number|null|undefined)=>n==null?"—":Number(n).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const sg=(n:number)=>n>0?"+":"";
export default function Dashboard({indices,vix,fii,dii,sectors,gainers,losers,stats}:{indices:I[];vix:{value:number;chg:number;chgPct:number};fii:number;dii:number;sectors:S[];gainers:M[];losers:M[];stats:{advances:number;declines:number;unchanged:number}}){
 const heat=(n:number)=>n>=0?`rgba(49,209,124,${Math.min(.9,.25+Math.abs(n)/4)})`:`rgba(255,92,87,${Math.min(.9,.25+Math.abs(n)/4)})`;
 const cr=(n:number)=>`₹${Math.abs(n).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})} Cr`;
 return <><h1 className="page-title">Dashboard</h1><div className="sub">Market overview and option-flow pulse. This is the React foundation; live backend comes next.</div>
 <div className="section grid4">{indices.map(i=><div className="card" key={i.symbol}><div className="label">{i.symbol}</div><div className="metric mono">{f(i.spot)}</div><div className={`mono ${i.chg>=0?"up":"down"}`}>{sg(i.chg)}{f(i.chg)} ({sg(i.chgPct)}{f(i.chgPct)}%)</div><div className="hr"/><div className="row"><span className="sub">Future</span><b className="mono">{f(i.future)}</b></div><div className="row"><span className="sub">VWAP</span><b className="mono">{f(i.vwap)}</b></div><div className="row"><span className="sub">PCR OI</span><b className="mono">{f(i.pcrOI)}</b></div><div className="row"><span className="sub">PCR COI</span><b className="mono">{f(i.pcrCOI)}</b></div></div>)}</div>
 <div className="section grid2"><div className="card"><h3>PCR & ATM Ladder</h3><div className="sub">PCR &gt; 1 = more put activity; PCR &lt; 1 = more call activity.</div><div className="grid4" style={{marginTop:14}}>{indices.map(i=><div className="card" style={{background:"var(--panel2)",padding:11}} key={i.symbol}><div className="label">{i.symbol}</div><div className={`metric mono ${i.pcrOI>=1?"up":"down"}`} style={{fontSize:21}}>{f(i.pcrOI)}</div></div>)}</div><div style={{overflowX:"auto",marginTop:10}}><table><thead><tr><th>Index</th><th>ATM</th><th>Support</th><th>Resistance</th></tr></thead><tbody>{indices.map(i=><tr key={i.symbol}><td style={{fontFamily:"inherit",fontWeight:700}}>{i.symbol}</td><td>{f(i.atm)}</td><td className="up">{f(i.support)}</td><td className="down">{f(i.resistance)}</td></tr>)}</tbody></table></div></div>
 <div className="card"><h3>India VIX</h3><div className="row" style={{marginTop:10}}><div><div className="metric mono">{f(vix.value)}</div><div className="sub">{vix.value<15?"Low volatility regime":vix.value<20?"Moderate volatility":"Elevated volatility"}</div></div><div className={`mono ${vix.chg>=0?"up":"down"}`}>{sg(vix.chg)}{f(vix.chg)} ({sg(vix.chgPct)}{f(vix.chgPct)}%)</div></div><div className="chart">India VIX chart — live trend will be connected next.</div></div></div>
 <div className="section grid2"><div className="card"><h3>Sector Heatmap</h3><div className="heat" style={{marginTop:12}}>{sectors.map(s=><div className="heat-item" style={{background:heat(s.chg)}} key={s.name}><span>{s.name.replace("NIFTY ","")}</span><b>{sg(s.chg)}{f(s.chg)}%</b></div>)}</div></div><div className="card"><h3>FII / DII</h3><div className="grid2" style={{marginTop:12}}><div className="card" style={{background:"var(--panel2)"}}><div className="label">FII Net</div><div className="smallmetric mono">{cr(fii)}</div><div className="sub">{fii>=0?"NET BUY":"NET SELL"}</div></div><div className="card" style={{background:"var(--panel2)"}}><div className="label">DII Net</div><div className="smallmetric mono">{cr(dii)}</div><div className="sub">{dii>=0?"NET BUY":"NET SELL"}</div></div></div></div></div>
 <div className="section grid2">{[["Top Gainers",gainers],["Top Losers",losers]].map(([title,a])=><div className="card" key={String(title)}><h3>{String(title)}</h3>{(a as M[]).map(m=><div className="row" style={{padding:"8px 0",borderBottom:"1px solid var(--line)"}} key={m.symbol}><span>{m.symbol}</span><span className={`mono ${m.chg>=0?"up":"down"}`}>{f(m.price)} {sg(m.chg)}{f(m.chg)}%</span></div>)}</div>)}</div>
 <div className="section card"><h3>Market Breadth</h3><div className="grid4" style={{marginTop:12}}>{[["Advances",stats.advances,"up"],["Declines",stats.declines,"down"],["Unchanged",stats.unchanged,""],["Net",stats.advances-stats.declines,stats.advances>=stats.declines?"up":"down"]].map(x=><div className="card" key={String(x[0])}><div className="label">{String(x[0])}</div><div className={`smallmetric mono ${x[2]}`}>{Number(x[1]).toLocaleString("en-IN")}</div></div>)}</div></div></>;
}
